In [1]:
import numpy as np

In [2]:
N = 3
# t_org = np.arange(N)
# pi = np.random.permutation(N)
fake_measures = np.array([np.random.randn(100)*k for k in range(1, N+1)])
covmatrix = np.cov(fake_measures)
print("Original covariance matrix", covmatrix, sep="\n")


Original covariance matrix
[[0.90893157 0.14449112 0.31942154]
 [0.14449112 3.49366035 0.0463234 ]
 [0.31942154 0.0463234  7.67769049]]


In [4]:
#%% Alternative using Permutation matrix
p = np.random.permutation(N)
P = np.eye(N)[p]
print(p)
print("Permutation matrix", P, sep="\n")

[2 1 0]
Permutation matrix
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [6]:
p1 = P@covmatrix@P.T
print("Reconstruction:", p1, sep="\n")

Reconstruction:
[[7.67769049 0.0463234  0.31942154]
 [0.0463234  3.49366035 0.14449112]
 [0.31942154 0.14449112 0.90893157]]


In [8]:
print("Reconstruction equals original:", p1 == covmatrix, sep="\n")

Reconstruction equals original:
[[False False  True]
 [False  True False]
 [ True False False]]


In [19]:
import scipy.special as sp
# a = [0, 1, 0, 2]
# perm = np.arange(31)
perms = sp.perm(31, 2)
perms

930.0